### ISSUE TITLE
16 August 2021 - InnerSource SIG Meeting Minutes

### ISSUE THREAD

**Issue by mcleo-d** [finos/InnerSource#27]
## Date
Monday 16 August 2021 - 11am EST / 4pm UK

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **SIG Leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS SIG meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Review FINOS Slack InnerSource SIG Channel - https://finos-lf.slack.com/archives/C01SYB503QT
- [ ] Agenda item 1
- [ ] Agenda item 2
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info
- Webex : https://finos.webex.com/finos/j.php?MTID=m33975a6a163e1319c07e33a06bd3d1d5
- Meeting number: 127 765 4882

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 127 765 4882

### Mailing List
Email innersource+subscribe@finos.org to subscribe to the InnerSource SIG mailing list.

**Comment by amaltson** [comment]
👋

**Comment by claredillon** [comment]
Hello

**Comment by clcoffey** [comment]
Hi

**Comment by eminty69** [comment]
Hello

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by claredillon** [comment]
Danese Cooper also present

**Comment by claredillon** [comment]
Minutes Notes (with thanks to @clcoffey who did a lot of the sciribing!)

## Sign off Previous Minutes 
- If there are no objections within the next 24 hours, we will sign off on the previous meeting minutes.

## Update from InnerSource Slack channel
- There has been no action on the InnerSource Slack channel since last meeting.
- Some reported issues signing up. Invite has been sent from Slack. Suggestion from Jane to reach out to FINOS help if there are continuing issues. 

## Update from OSR SIG
- Clare attended [OSR SIG](https://github.com/finos/open-source-readiness) and will continue to attend to represent InnerSource SIG (all welcome to join!).
- Their first deliverable will be a maturity matrix, which includes reference to InnerSource.
- Call on the InnerSource SIG to engage to review in two ways: (1) the format - we should agree a format for submitting into GitHub for both; (2) the content 

## OSSF Event
- InnerSource SIG panel was accepted, but we have to be there in person, and many can’t make it. Open call for members who will be there in person, and available to share experiences to let us know. 

## Next focus for SIG

Awesome-style list
- Agreed we will work on this, first in discussions, to get ideas, and decide on categories.
- ACTION: Clare to open discussion on Awesome-style list

InnerSource Maturity Matrix
- Waiting for James to get the latest on licensing.
- Discussion about which platform to use. Agreed we should submit as GitHub Markdown. One proposal is Docusource. Need to get feedback from James about what is standard FINOS practice. 
- Call also for examples of favourite formats for maturity matrices.
- Once it is in GitHub, example docs can be added later via PR.
- ACTION: Clare to open discussion about what platform to use for submitting docs and ideal format.

Case Studies
- Agreed case studies would be a good idea. Two types discussed: 

1. Simple reference case studies - evidence of InnerSource
2. Deeper case studies, examining issues, anonymised.
