### ISSUE TITLE
Edit Page on every site is broken

### ISSUE THREAD

**Issue by anvacca** [finos/InnerSource#68]
### Steps to Reproduce:
 1. Visit any page on the InnerSource.finos.org site e.g. https://innersource.finos.org/docs/intro 
 2. Scroll to the bottom and click "Edit this page"
 
### Expected Result:
Taken to the github repo/page

### Actual Result:
404 error on page not found

### Environment:
Latest version

### Additional Context:
this issues can be created on every issue as the master template is broken.

**Comment by gravax** [comment]
Confirmed here.

**Comment by spier** [comment]
I suspect that this happens because the source files live in: `https://github.com/finos/InnerSource/tree/master/docs`
However the "Edit" links mentioned in this issue point to: `https://github.com/finos/open-developer-platform/...`

The misconfiguration might stem from here:
https://github.com/finos/InnerSource/blob/master/website/docusaurus.config.js#L115
